tap "datadog-labs/pack"

brew "datadog-labs/pack/pup"
brew "fish"
brew "fzf"
brew "gh"
brew "gpg"
brew "jq"
brew "kubernetes-cli"
brew "libpq"
brew "mise"
brew "nvim"
brew "pv"
brew "tfenv"
brew "the_platinum_searcher"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vale"
brew "watch"

cask "1password"
cask "aws-vault-binary"
cask "claude-code"
cask "font-source-code-pro"
cask "gcloud-cli"
cask "iterm2"
